### ISSUE TITLE
Getting error on npm start command

### ISSUE THREAD

**Issue by 2anant** [jmcooper/ng2-fundamentals#22]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.1.2
3 info using node@v7.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ng2-fundamentals-demo@1.0.0~prestart: ng2-fundamentals-demo@1.0.0
6 silly lifecycle ng2-fundamentals-demo@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle ng2-fundamentals-demo@1.0.0~start: ng2-fundamentals-demo@1.0.0
8 verbose lifecycle ng2-fundamentals-demo@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ng2-fundamentals-demo@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\angularwork\ng2-fundamentals-master\node_modules\.bin;C:\Users\anantaraj.sajjan\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\anantaraj.sajjan\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\Dell\Dell Data Protection\Drivers\TSS\bin;C:\Program Files\nodejs;C:\Users\anantaraj.sajjan\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle ng2-fundamentals-demo@1.0.0~start: CWD: D:\angularwork\ng2-fundamentals-master
11 silly lifecycle ng2-fundamentals-demo@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'tsc && concurrently "npm run tsc:w" "npm run server" ' ]
12 silly lifecycle ng2-fundamentals-demo@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle ng2-fundamentals-demo@1.0.0~start: Failed to exec start script
14 verbose stack Error: ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ng2-fundamentals-demo@1.0.0
16 verbose cwd D:\angularwork\ng2-fundamentals-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v7.6.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
22 error Exit status 1
23 error Failed at the ng2-fundamentals-demo@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run server" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ng2-fundamentals-demo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "npm run tsc:w" "npm run server"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ng2-fundamentals-demo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ng2-fundamentals-demo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by 2anant** [comment]
i am using node 7.6.0 verison, let me know is any thing missed, i just downloaded and started npm install and then npm start, getting error,

**Comment by 2anant** [comment]
i tried in git bash so didnt work it seems, i opened new cmd window and started npm . its working.
